//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CaseFileRequester.Logic.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("camara")]
        public string Query_Camera {
            get {
                return ((string)(this["Query_Camera"]));
            }
            set {
                this["Query_Camera"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("numero")]
        public string Query_File {
            get {
                return ((string)(this["Query_File"]));
            }
            set {
                this["Query_File"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("anio")]
        public string Query_Year {
            get {
                return ((string)(this["Query_Year"]));
            }
            set {
                this["Query_Year"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("j_idt24:menuNavigation:j_idt51:j_idt57")]
        public string Login_Logout {
            get {
                return ((string)(this["Login_Logout"]));
            }
            set {
                this["Login_Logout"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("consultaFiltroSearchButtonSAU")]
        public string Query_Submit {
            get {
                return ((string)(this["Query_Submit"]));
            }
            set {
                this["Query_Submit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::CaseFileRequester.Entities.Lawers Lawers {
            get {
                return ((global::CaseFileRequester.Entities.Lawers)(this["Lawers"]));
            }
            set {
                this["Lawers"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string Main_Site {
            get {
                return ((string)(this["Main_Site"]));
            }
            set {
                this["Main_Site"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("username")]
        public string Login_User {
            get {
                return ((string)(this["Login_User"]));
            }
            set {
                this["Login_User"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("password")]
        public string Login_Pass {
            get {
                return ((string)(this["Login_Pass"]));
            }
            set {
                this["Login_Pass"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("kc-login")]
        public string Login_Submit {
            get {
                return ((string)(this["Login_Submit"]));
            }
            set {
                this["Login_Submit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("menuLoginId")]
        public string Main_Login {
            get {
                return ((string)(this["Main_Login"]));
            }
            set {
                this["Main_Login"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("btn-lista-relacionados")]
        public string Query_RelatedFiles {
            get {
                return ((string)(this["Query_RelatedFiles"]));
            }
            set {
                this["Query_RelatedFiles"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://scw.pjn.gov.ar/scw/homePrivado.seam")]
        public string Query_Site {
            get {
                return ((string)(this["Query_Site"]));
            }
            set {
                this["Query_Site"] = value;
            }
        }
    }
}
